name: Docker Image CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    mindmapper-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and export to Docker
              uses: docker/build-push-action@v2
              with:
                  context: .
                  target: development
                  push: true
                  tags: |
                      ghcr.io/b310-digital/mindmapper/ci:${{ github.sha }}-dev
            #   outputs: type=docker,dest=/tmp/myimage.tar

            # - name: Upload artifact
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: myimage
            #       path: /tmp/myimage.tar

    mindmapper-backend-lint-2:
        runs-on: ubuntu-latest
        needs: mindmapper-build
        container:
            image: ghcr.io/b310-digital/mindmapper/ci:${{ github.sha }}-dev
            options: --user root

        steps:
            - run: pwd
            - run: ls -lisa
            - run: ls -lisa /
            - run: ls -lisa /home/node/app
            - uses: actions/checkout@v2
            - run: pwd
            - run: ls -lisa
            - run: ls -lisa mindmapper-backend
            - run: ls -lisa mindmapper-backend/node_modules
            - run: ls -lisa mindmapper-backend/src
            - run: npm --prefix mindmapper-backend run lint

    mindmapper-backend-test-e2e-2:
        runs-on: ubuntu-latest
        needs: mindmapper-build
        container:
            image: ghcr.io/b310-digital/mindmapper/ci:${{ github.sha }}-dev
            options: --user root

        services:
            postgres:
                image: postgres:10.8
                env:
                    POSTGRES_USER: mindmapper-user
                    POSTGRES_PASSWORD: mindmapper-password
                    POSTGRES_DB: mindmapper-backend-test
                ports:
                    # Will assign a random free host port
                    - 5432/tcp
                # Needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - run: pwd
            - run: ls -lisa
            - uses: actions/checkout@v2
            - run: pwd
            - run: ls -lisa
            - run: ls -lisa mindmapper-backend
            - run: ls -lisa mindmapper-backend/node_modules
            - run: ls -lisa mindmapper-backend/src
            - run: npm --prefix mindmapper-backend run test:e2e
              env:
                  POSTGRES_DATABASE: "mindmapper-backend-test"
                  POSTGRES_HOST: "postgres"
                  POSTGRES_PASSWORD: "mindmapper-password"
                  POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
                  POSTGRES_SSL: false
                  POSTGRES_TEST_DATABASE: "mindmapper-backend-test"
                  POSTGRES_TEST_HOST: "postgres"
                  POSTGRES_TEST_PASSWORD: "mindmapper-password"
                  POSTGRES_TEST_PORT: ${{ job.services.postgres.ports[5432] }}
                  POSTGRES_TEST_USER: "mindmapper-user"
                  POSTGRES_USER: "mindmapper-user"


    mindmapper-frontend-lint-2:
        runs-on: ubuntu-latest
        needs: mindmapper-build
        container:
            image: ghcr.io/b310-digital/mindmapper/ci:${{ github.sha }}-dev
            options: --user root

        steps:
            - run: pwd
            - run: ls -lisa
            - uses: actions/checkout@v2
            - run: pwd
            - run: ls -lisa
            - run: ls -lisa mindmapper-frontend
            - run: ls -lisa mindmapper-frontend/node_modules
            - run: ls -lisa mindmapper-frontend/src
            - run: npm --prefix mindmapper-frontend run lint

    mindmapper-backend-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: npm --prefix mindmapper-backend ci

            - run: npm --prefix mindmapper-backend run lint

    mindmapper-backend-test-e2e:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:10.8
                env:
                    POSTGRES_USER: mindmapper-user
                    POSTGRES_PASSWORD: mindmapper-password
                    POSTGRES_DB: mindmapper-backend-test
                ports:
                    # Will assign a random free host port
                    - 5432/tcp
                # Needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v2

            - run: npm --prefix mindmapper-backend ci

            - run: npm --prefix mindmapper-backend run test:e2e
              env:
                  POSTGRES_DATABASE: "mindmapper-backend-test"
                  POSTGRES_HOST: "localhost"
                  POSTGRES_PASSWORD: "mindmapper-password"
                  POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
                  POSTGRES_SSL: false
                  POSTGRES_TEST_DATABASE: "mindmapper-backend-test"
                  POSTGRES_TEST_HOST: "localhost"
                  POSTGRES_TEST_PASSWORD: "mindmapper-password"
                  POSTGRES_TEST_PORT: ${{ job.services.postgres.ports[5432] }}
                  POSTGRES_TEST_USER: "mindmapper-user"
                  POSTGRES_USER: "mindmapper-user"
